#!/usr/bin/env node
const fs = require('fs');
const path = require('path');

const IT = {
  1:{s:"Se non puoi smontare il messaggio, sporca il messaggero.",h:"«Certo che dici così, sei pagato per dirlo.» — e nessuno guarda più i dati.",a:{bait:"Qualcuno fa un'affermazione scomoda ma documentata.",hook:"Invece di contestare i dati, si attacca chi parla: identità, passato, motivi.",trap:"Il pubblico scarta la persona, e con essa anche l'argomento."}},
  2:{s:"Una risata seppellisce più di mille confutazioni.",h:"Un meme-caricatura del politico col naso rosso gira nelle chat: nessuno discute più la sua proposta.",a:{bait:"Un avversario con un'idea difficile da contrastare.",hook:"Lo si trasforma in caricatura: soprannome, voce storpiata, meme.",trap:"Ridere di qualcuno vale quanto averlo sconfitto: l'idea muore con la risata."}},
  3:{s:"Trasforma l'avversario in mostro: la discussione diventa caccia.",h:"«Non sono cittadini con idee diverse, sono un'invasione.» — e il dialogo è finito.",a:{bait:"Un gruppo di persone con posizioni legittime ma contrarie.",hook:"Gli si attribuiscono tratti subumani, intenti distruttivi, minaccia esistenziale.",trap:"Non si negozia con un mostro: si elimina. Il contraddittorio è già perso."}},
  4:{s:"Se non puoi convincere, inonda fino alla rinuncia.",h:"Cinque versioni contraddittorie dello stesso evento in 24 ore: a fine giornata nessuno sa più cosa sia successo.",a:{bait:"Un fatto verificabile che andrebbe contestato.",hook:"Si spara un diluvio di messaggi rapidi, contraddittori, su tutti i canali.",trap:"Il pubblico, esausto, smette di cercare la verità: ogni versione sembra una opinione."}},
  5:{s:"L'urgenza finta è il carburante della disinformazione.",h:"«Inoltra a 10 amici entro sera o succederà il peggio!» — il messaggio moltiplica sé stesso.",a:{bait:"Una notizia scioccante, una minaccia, un'occasione.",hook:"Si chiede esplicitamente di inoltrare subito, senza verificare.",trap:"Ogni utente diventa un nodo: il messaggio esce dal radar dei fact-checker."}},
  6:{s:"Chi sceglie la cornice, vince il quadro.",h:"Non è un «aumento delle tasse», è una «riforma della fiscalità». Stessa misura, reazioni opposte.",a:{bait:"Un tema complesso che può essere letto in molti modi.",hook:"Si sceglie il lessico, l'angolo, il paragone — e lo si ripete.",trap:"Il pubblico pensa dentro quella cornice senza accorgersi di averla indossata."}},
  7:{s:"«E voi allora?» è il paralume che oscura ogni critica.",h:"«Parli di corruzione qui? E gli scandali di 20 anni fa nell'altro partito?» — e la critica originale svanisce.",a:{bait:"Una critica precisa che andrebbe affrontata.",hook:"Invece di rispondere, si punta il dito altrove: «e loro?».",trap:"La discussione si sposta, nessuno risponde alla domanda iniziale."}},
  8:{s:"I media non ti dicono cosa pensare, ma a cosa pensare.",h:"Per settimane il TG apre con la cronaca nera. Il paese si sente meno sicuro, anche se i reati calano.",a:{bait:"Un flusso quotidiano di temi possibili.",hook:"Alcuni vengono ripetuti in apertura, altri ignorati.",trap:"Il pubblico crede che l'importante sia ciò che è visibile, non ciò che conta davvero."}},
  9:{s:"Avvelena la fonte prima che beva qualcuno.",h:"«Prima che parli, sappiate che è stato indagato nel 2012.» — la testimonianza è già incrinata.",a:{bait:"Qualcuno che sta per dire qualcosa di credibile.",hook:"Prima che parli, si introducono informazioni negative sulla sua persona.",trap:"Qualsiasi cosa dirà, il pubblico la ascolterà con sospetto preventivo."}},
  10:{s:"Metà verità, intera bugia.",h:"Un volantino elenca solo i successi del candidato, mai i fallimenti. Tutto vero. Tutto parziale.",a:{bait:"Una storia complessa con luci e ombre.",hook:"Si presentano solo i dati a favore, tacendo il resto.",trap:"Nessuna bugia esplicita, ma il quadro finale è distorto."}},
  11:{s:"Dagli un'etichetta e non dovrai più discutere con lui.",h:"«È un negazionista.» Bastano due parole: la discussione è sostituita da una categoria.",a:{bait:"Una posizione articolata e sfumata.",hook:"Si appiccica un'etichetta semplice, carica emotivamente.",trap:"L'etichetta copre la persona: non si discute più con lei, si discute con la categoria."}},
  12:{s:"Se lo fanno tutti, devi farlo anche tu. Anche se non serve.",h:"«Il 72% degli italiani è d'accordo con noi.» — il tuo cervello corre a unirsi al 72%.",a:{bait:"Il bisogno umano di non restare isolati.",hook:"Si mostra un numero, un movimento, una massa che \"già\" la pensa così.",trap:"Salti sul carro per non essere escluso, non perché hai valutato."}},
  13:{s:"Parole luminose che non dicono niente.",h:"«Libertà, futuro, cambiamento.» — applauso. Cosa significa concretamente? Nessuno lo chiede.",a:{bait:"Valori che tutti condividono e nessuno contesta.",hook:"Si usano parole astratte e nobili senza definirle né impegnarsi.",trap:"Aderisci al bagliore e accetti qualsiasi contenuto che viene infilato dentro."}},
  14:{s:"Rubare l'autorità altrui appoggiandovisi sopra.",h:"Il politico davanti alla bandiera, accanto alla statua di un eroe nazionale: il messaggio cambia senza dire una parola.",a:{bait:"Un simbolo rispettato (bandiera, scienza, religione, eroe).",hook:"Si affianca il proprio messaggio al simbolo.",trap:"Le emozioni legate al simbolo si trasferiscono sul messaggio, senza prove."}},
  15:{s:"Un volto famoso al posto di un argomento.",h:"Un attore amato dice «fidatevi di questo farmaco»: non è un medico, ma la sua faccia vale più dei dati.",a:{bait:"L'affetto del pubblico per un personaggio noto.",hook:"Il personaggio approva una tesi, un prodotto, un'idea.",trap:"La simpatia verso la persona diventa fiducia nella tesi."}},
  16:{s:"Ripeti una cosa abbastanza volte e diventa vera.",h:"Lo stesso slogan a ogni intervista, ogni tweet, ogni manifesto. Dopo un mese, ti sembra di averlo sempre pensato.",a:{bait:"Un'affermazione, vera o falsa, che si vuole far passare.",hook:"La si ripete identica, con frequenza alta, su più canali.",trap:"La familiarità diventa credibilità: riconoscere = credere."}},
  17:{s:"Una frase corta può uccidere un'ora di ragionamento.",h:"«Prima gli italiani.» Tre parole: nessun argomento resiste senza diventare lungo, complicato, noioso.",a:{bait:"Una realtà complessa che richiede spiegazioni.",hook:"Si comprime in una formula ritmica, memorabile, emotiva.",trap:"La formula diventa la conclusione: il pensiero critico costa troppo in confronto."}},
  18:{s:"Il potente in camicia a maniche corte non è uno di noi: finge di esserlo.",h:"Il miliardario in felpa, che beve birra in un bar di paese: «sono come te». (Spoiler: no.)",a:{bait:"La diffidenza verso le élite.",hook:"Chi comanda si veste, parla, mangia come la \"gente comune\".",trap:"Ti fidi di lui perché sembra come te — smetti di vedere il potere che detiene."}},
  19:{s:"Un titolo non è una prova: controlla il campo.",h:"«Un Premio Nobel ha detto che...» — sì, ma Nobel in letteratura che parla di medicina. Il titolo abbaglia.",a:{bait:"Il rispetto istintivo per i titoli e le competenze.",hook:"Si cita un'autorità, anche fuori dal suo campo, come se fosse conclusiva.",trap:"Il prestigio del titolo sostituisce la verifica dell'argomento."}},
  20:{s:"Rompi il centro. Solo estremi. Solo nemici.",h:"«O con noi o con loro.» Chi cerca di mediare diventa traditore di entrambi i lati.",a:{bait:"Una società fatta di tante posizioni sfumate.",hook:"Si riducono i campi a due, ostili, incompatibili.",trap:"Chi sta in mezzo scompare o diventa bersaglio: il dialogo è eliminato."}},
  21:{s:"Venti bugie in un minuto: nessuno riesce a confutarle tutte.",h:"In dibattito snocciola 15 \"fatti\" sospetti in 90 secondi. Confutarli richiederebbe mezz'ora. Non la hai.",a:{bait:"Il formato limitato di un dibattito o intervista.",hook:"Si spara una raffica di affermazioni false o dubbie troppo veloci da smontare.",trap:"L'avversario risponde a poche, tutte le altre rimangono valide per il pubblico."}},
  22:{s:"Non attacca te: attacca una versione ridicola di te.",h:"«Vuoi limitare la velocità in città?» → «Quindi vuoi vietare le auto!» — e la discussione si sposta su qualcosa che non hai detto.",a:{bait:"Una posizione ragionevole ma difficile da contrastare.",hook:"Si riformula in versione estrema, caricaturale, facile da attaccare.",trap:"L'avversario demolisce la caricatura e tu sembri aver perso, pur non avendo detto quello."}},
  23:{s:"Un diversivo profumato, e la pista si perde.",h:"Gli chiedi del bilancio: risponde parlando della stagione calcistica. A metà risposta, hai dimenticato la domanda.",a:{bait:"Una domanda scomoda e specifica.",hook:"Si introduce un argomento interessante ma irrilevante.",trap:"La conversazione segue la nuova pista; la domanda originale muore."}},
  24:{s:"Accusa l'altro di ciò che stai facendo tu.",h:"Il politico coinvolto in scandali grida ogni giorno: «Sono loro i corrotti!». Chi ascolta si confonde.",a:{bait:"Una propria colpa che potrebbe emergere.",hook:"Si accusa l'avversario dello stesso atto, per primo e con clamore.",trap:"Il pubblico fatica a distinguere chi è davvero colpevole: il rumore copre la pista."}},
  25:{s:"Parli a tutti, ma solo alcuni sentono il vero messaggio.",h:"Una frase apparentemente innocua: «restituire la nostra terra a chi la merita». Gli insider ricevono il codice.",a:{bait:"Un pubblico misto che va gestito.",hook:"Si usa un linguaggio neutro per i più, codificato per un sottogruppo.",trap:"Se qualcuno denuncia il sottinteso, basta negare: «non l'ho mai detto»."}},
  26:{s:"Ti fa dubitare di ciò che hai visto con i tuoi occhi.",h:"«Non è mai successo.» «Te lo sei immaginato.» «Sei troppo sensibile.» — dopo mesi, non sai più cosa è vero.",a:{bait:"Un episodio reale, documentato o vissuto.",hook:"Si nega con calma, ripetutamente, che sia mai accaduto o che fosse come sembrava.",trap:"La vittima smette di fidarsi della propria memoria: perde la bussola."}},
  27:{s:"Scegli le ciliegie buone. Lascia marcire il resto sotto l'albero.",h:"Un solo studio su 100 dà ragione alla tesi. Lo cita come \"la scienza dice che\". Gli altri 99? Silenzio.",a:{bait:"Un insieme ampio di dati, molti contrari alla tesi.",hook:"Si estraggono solo i casi che confermano.",trap:"Il campione diventa bugia statistica senza che nessuna singola affermazione sia, in sé, falsa."}},
  28:{s:"Prato finto: sembra spontaneo, è un tappeto.",h:"Una \"associazione di cittadini\" appare in 50 città lo stesso giorno, stessa grafica. Nessuno si fa domande.",a:{bait:"La fiducia che le persone ripongono nei movimenti dal basso.",hook:"Si finanzia e organizza un \"movimento\" che simula la spontaneità popolare.",trap:"Il pubblico crede di vedere volontà popolare, invece guarda uno spot pagato."}},
  29:{s:"Colpisciti da solo, incolpa il tuo nemico.",h:"Un attacco apparentemente compiuto dal gruppo A viene attribuito al gruppo B per giustificarne la repressione.",a:{bait:"La necessità di una giustificazione per un'azione forte.",hook:"Si mette in scena un'aggressione facendola sembrare opera dell'avversario.",trap:"L'opinione pubblica chiede vendetta contro un nemico che non ha agito."}},
  30:{s:"I tuoi occhi non bastano più come prova.",h:"Un video del leader che dice cose mai dette. Virale in 6 ore. La smentita, in 6 giorni.",a:{bait:"La fiducia residua che le persone ripongono nei video e nell'audio.",hook:"Si sintetizza un contenuto falso ma visivamente identico all'originale.",trap:"Anche quando smascherato, il ricordo emotivo del video resta."}},
  31:{s:"Una guerra senza armi: il campo di battaglia è la tua testa.",h:"Centinaia di account fake, articoli coordinati, meme su misura: non un singolo atto, una campagna orchestrata.",a:{bait:"Uno spazio informativo aperto e fragile.",hook:"Attori statali o privati coordinano contenuti, account, canali in campagne durature.",trap:"Il dibattito pubblico di una nazione viene plasmato dall'esterno, senza dichiarazioni di guerra."}},
  32:{s:"Non nascondere la notizia: seppelliscila sotto altre notizie.",h:"Il giorno dell'inchiesta scomoda esce una \"notizia bomba\" sulla vita privata di un VIP: l'inchiesta sparisce.",a:{bait:"Una notizia scomoda che emergerebbe da sola.",hook:"Si rilasciano contemporaneamente molti contenuti più spettacolari.",trap:"L'attenzione è una risorsa scarsa: la notizia importante non trova spazio."}},
  33:{s:"Spaventali e non penseranno: obbediranno.",h:"«Se non agiamo oggi, domani sarà troppo tardi!» — e qualsiasi misura drastica diventa accettabile.",a:{bait:"Un'ansia latente o un pericolo reale.",hook:"Si amplifica la minaccia e si offre una soluzione immediata e forte.",trap:"Il pubblico, terrorizzato, accetta compromessi che, a mente fredda, rifiuterebbe."}},
  34:{s:"La bandiera come argomento: chi la tocca è nemico.",h:"«Un vero italiano non dubiterebbe mai di questa misura.» — e il dissenso diventa tradimento.",a:{bait:"L'attaccamento emotivo alla patria.",hook:"Si lega una tesi specifica all'identità nazionale.",trap:"Criticare la tesi equivale a tradire la nazione: il dissenso costa troppo."}},
  35:{s:"Non vende il prodotto: vende chi vorresti essere.",h:"Una modella ride in una cucina perfetta con in mano un detersivo. Non compri il detersivo: compri quella vita.",a:{bait:"Il desiderio di assomigliare a persone attraenti e di successo.",hook:"Si associa il prodotto o l'idea a corpi e vite perfette.",trap:"Aderire alla tesi diventa il modo per avvicinarsi a quella immagine."}},
  36:{s:"«Ultimi posti!» spegne il cervello.",h:"«Solo 3 articoli rimasti!» — clicchi prima di chiederti se ti serve.",a:{bait:"La paura di perdere un'occasione.",hook:"Si segnala scarsità o urgenza, vera o inventata.",trap:"Il cervello passa alla modalità \"agire subito\" e salta la valutazione."}},
  37:{s:"Un regalo oggi è una catena domani.",h:"Ti offrono un campione gratis. Ora senti il bisogno di ricambiare: è così che funziona la tua testa.",a:{bait:"La norma sociale universale: \"dono e contraccambio\".",hook:"Si fa un piccolo favore o regalo gratuito.",trap:"La persona avverte un debito morale e concede cose sproporzionate rispetto al regalo."}},
  38:{s:"Il primo numero vince il negoziato, anche se è assurdo.",h:"Prezzo di listino: 999€. Scontato: 299€. L'«occasione» esiste solo perché hai visto 999€ per primo.",a:{bait:"La necessità di avere un punto di riferimento.",hook:"Si lancia un primo valore (prezzo, stima, percentuale) alto o basso a piacere.",trap:"Ogni valutazione successiva ruota attorno all'ancora, anche se arbitraria."}},
  39:{s:"Cerchiamo ciò che già crediamo e lo chiamiamo prova.",h:"Leggi solo il giornale che la pensa come te. Dopo un anno, sei convinto che «tutti» la pensino così.",a:{bait:"La tendenza naturale del cervello a confermare le proprie tesi.",hook:"Si offrono continuamente contenuti in linea con le tue convinzioni.",trap:"Percepisci il mondo come unanime: il dubbio sparisce dal radar."}},
  40:{s:"O bianco o nero: tutto il resto è stato cancellato.",h:"«O sei con noi o sei contro di noi.» — il terzo, il quarto, il decimo scenario sono stati spazzati via.",a:{bait:"Una realtà con molte opzioni possibili.",hook:"Si presentano solo due alternative, estreme e contrapposte.",trap:"Scegli la \"meno peggio\" senza accorgerti delle opzioni nascoste."}},
  41:{s:"Ti riempie d'amore per legarti al guinzaglio.",h:"Nei primi giorni sei inondato di attenzioni, regali, complimenti. Mesi dopo, non riesci a uscirne.",a:{bait:"Il bisogno universale di sentirsi visti e amati.",hook:"Si satura la vittima di affetto intenso e improvviso.",trap:"Quando l'amore viene tolto, faresti di tutto per riaverlo: sei in trappola."}},
  42:{s:"Non puoi recuperare ciò che hai già perso, ma ci provi lo stesso.",h:"«Ho già investito 5 anni: non posso mollare ora.» — ed eccoti a perderne altri 5.",a:{bait:"Un investimento passato non recuperabile (tempo, soldi, emozioni).",hook:"Si evoca ciò che si è già speso come motivo per continuare.",trap:"Si prende la decisione guardando il passato invece del futuro: si sprofonda."}},
  43:{s:"Una qualità bella ne fa brillare altre inesistenti.",h:"Il candidato è bello e sorride: il pubblico gli attribuisce competenza, onestà, intelligenza. Senza prove.",a:{bait:"Una qualità evidente e positiva (bellezza, fama, eloquenza).",hook:"Il cervello estende quel bagliore ad altri tratti non verificati.",trap:"Giudichi la persona sui meriti inventati dal tuo stesso cervello."}},
  44:{s:"«Naturale» non vuol dire «buono». L'arsenico è naturale.",h:"«È un rimedio naturale!» — come la cicuta, o il morso di vipera. Naturali pure quelli.",a:{bait:"Il fascino culturale per tutto ciò che è «naturale».",hook:"Si etichetta una cosa come «naturale» per implicarne bontà o sicurezza.",trap:"L'etichetta sostituisce la valutazione di rischi, efficacia, interazioni."}},
  45:{s:"Un piccolo passo oggi, il baratro domani (dicono loro).",h:"«Se permettiamo A, fra dieci anni avremo Z.» — senza mai spiegare cosa succede fra B e Y.",a:{bait:"Una proposta ragionevole e limitata.",hook:"Si proietta una catena di conseguenze catastrofiche senza tappe intermedie.",trap:"Il timore dell'esito finale blocca la discussione del passo iniziale, che era innocuo."}},
  46:{s:"Due cose confrontabili non sono automaticamente uguali.",h:"«Entrambi i partiti hanno scandali.» Sì, ma uno ha 3 inchieste, l'altro 300. La pari è retorica, non reale.",a:{bait:"Due situazioni paragonabili su qualche aspetto.",hook:"Si trattano come equivalenti ignorando scala, gravità, contesto.",trap:"Il pubblico conclude che «sono uguali» e chi è peggiore ci guadagna."}},
  47:{s:"Un problema complesso, una sola categoria da incolpare.",h:"Economia stagnante? Colpa di loro. Disoccupazione? Colpa di loro. Stadio pieno? Colpa di loro. Facile.",a:{bait:"Un malessere collettivo reale e diffuso.",hook:"Si identifica un gruppo su cui scaricare ogni responsabilità.",trap:"L'analisi delle cause vere si ferma: basta punire il capro espiatorio."}},
  48:{s:"Colpevole negato, vittima invertita.",h:"Viene accusato. Nega tutto. Attacca l'accusatore. Si presenta come vittima dell'inchiesta. In 30 secondi.",a:{bait:"Un'accusa fondata rivolta a chi ha potere.",hook:"Si nega, si attacca l'accusatore, si ribalta la parte di vittima e aggressore.",trap:"Il pubblico confuso non capisce più chi sta male e chi ha fatto male."}},
  49:{s:"Ieri era impensabile. Oggi è discutibile. Domani sarà legge.",h:"Un'idea estrema viene ripetuta con calma per anni. La prima volta scandalizza. Dopo cinque anni, è dibattito normale.",a:{bait:"Il range di ciò che una società considera dicibile.",hook:"Si introducono idee estreme che spostano i bordi poco alla volta.",trap:"Ciò che prima era tabù diventa normale, senza che nessuno lo decida esplicitamente."}},
  50:{s:"Credi di essere solo, quindi taci. Così diventi solo davvero.",h:"Sui social sembra che tutti la pensino così. Tu no, ma taci. E chi la pensa come te, vedendo il silenzio, tace anche lui.",a:{bait:"La paura dell'isolamento sociale.",hook:"Si amplifica una voce e si oscurano le altre, creando l'illusione di maggioranza.",trap:"I dissenzienti tacciono per paura, e il loro silenzio conferma l'illusione."}},
  51:{s:"Ogni volta che arrivi alla meta, la meta si sposta.",h:"«Prova X.» — lo provi. «Sì, ma ora prova Y.» — lo provi. «Sì, ma ora prova Z.» Il gioco è infinito.",a:{bait:"Una richiesta di prova o condizione chiara.",hook:"Ogni volta che viene soddisfatta, la si sostituisce con una nuova.",trap:"L'avversario non può mai «vincere»: la discussione è impostata per non finire mai."}},
  52:{s:"Un complimento avvelenato ti lega al donatore.",h:"«Sei carina, per una come te.» — ti senti insicura. Vuoi approvazione. La chiedi proprio a lui.",a:{bait:"L'autostima della vittima.",hook:"Si inseriscono critiche sottili dentro complimenti.",trap:"La vittima, destabilizzata, cerca approvazione proprio da chi l'ha destabilizzata."}},
  53:{s:"Non pensi: senti. E senti ciò che sentono gli altri.",h:"Un post indignato viene condiviso 10.000 volte. Prima ancora di leggerlo, sei già arrabbiato anche tu.",a:{bait:"La naturale sincronizzazione emotiva tra esseri umani.",hook:"Si diffondono contenuti ad alta carica emotiva in tempi rapidi.",trap:"L'emozione collettiva travolge il pensiero individuale: agisci prima di riflettere."}},
  54:{s:"Crea rumore dove non vuoi che guardino.",h:"Mentre il parlamento vota una legge controversa, scoppia un «caso» di costume che occupa tutti i TG.",a:{bait:"Un problema reale che potrebbe attirare attenzione critica.",hook:"Si genera o amplifica un evento distraente.",trap:"Quando il fumo si dirada, il problema è già diventato fatto compiuto."}},
  55:{s:"Prevedi il crollo e lo fai accadere.",h:"«Quella banca è a rischio.» Tutti corrono a ritirare i soldi. La banca crolla. Lo era davvero? Ora sì.",a:{bait:"Una previsione in un sistema dove le aspettative influenzano l'esito.",hook:"Si diffonde la previsione come fatto, modificando il comportamento collettivo.",trap:"Il comportamento modificato produce l'esito previsto, «confermando» la profezia."}},
  56:{s:"L'algoritmo ti dà ragione per tenerti attaccato.",h:"Sei mesi dopo, il tuo feed è fatto solo di cose che confermano ciò che pensi. Il mondo sembra piccolo e coerente.",a:{bait:"Il desiderio umano di contenuti «interessanti».",hook:"L'algoritmo impara cosa ti fa restare e ti mostra sempre più di quello.",trap:"Perdi il contatto con opinioni diverse: confondi la tua bolla col mondo."}}
};

const EN = {
  1:{s:"Can't break the message? Stain the messenger.",h:"«Of course you say that — you're paid to say it.» — and no one checks the data anymore.",a:{bait:"Someone makes an inconvenient but documented claim.",hook:"Instead of challenging the data, the speaker is attacked: identity, past, motives.",trap:"The audience discards the person — and the argument along with them."}},
  2:{s:"A laugh buries more than a thousand rebuttals.",h:"A clown-nosed meme of the politician floods the chats: no one talks about their proposal anymore.",a:{bait:"An opponent with an idea hard to refute.",hook:"Turn them into a caricature: nickname, distorted voice, meme.",trap:"Laughing at someone feels like defeating them: the idea dies with the laugh."}},
  3:{s:"Turn opponents into monsters: debate becomes a hunt.",h:"«They're not citizens with different ideas, they're an invasion.» — and dialogue is over.",a:{bait:"A group with legitimate but opposing positions.",hook:"Assign them subhuman traits, destructive intent, existential threat.",trap:"You don't negotiate with a monster — you eliminate it. Debate is already lost."}},
  4:{s:"Can't convince? Flood them until they give up.",h:"Five contradicting versions of the same event in 24 hours: by nightfall, nobody knows what actually happened.",a:{bait:"A verifiable fact that should be challenged.",hook:"Fire a flood of fast, contradictory messages across every channel.",trap:"Exhausted, the audience stops looking for truth: every version becomes just an opinion."}},
  5:{s:"Fake urgency is the fuel of disinformation.",h:"«Forward to 10 friends by tonight or else!» — and the message multiplies itself.",a:{bait:"A shocking story, a threat, an opportunity.",hook:"Ask explicitly to forward now, without checking.",trap:"Every user becomes a relay: the message escapes the fact-checkers' radar."}},
  6:{s:"Whoever picks the frame wins the picture.",h:"It's not a «tax hike», it's a «fiscal reform». Same measure, opposite reactions.",a:{bait:"A complex topic open to many readings.",hook:"Pick the words, the angle, the analogy — and repeat.",trap:"The audience thinks inside that frame without realizing they put it on."}},
  7:{s:"«What about you?» — the lampshade that dims every critique.",h:"«You're talking corruption here? What about the scandals 20 years ago in the other party?» — the original critique dissolves.",a:{bait:"A precise critique that needs an answer.",hook:"Instead of answering, point elsewhere: «and them?».",trap:"The discussion shifts; no one ever addresses the original question."}},
  8:{s:"The media don't tell you what to think — but what to think about.",h:"For weeks the news leads with crime. The country feels less safe — even as crime is falling.",a:{bait:"A daily river of possible topics.",hook:"Some get repeated at the top; others are ignored.",trap:"The public believes what's visible is what matters — not what actually matters."}},
  9:{s:"Poison the well before anyone drinks.",h:"«Before he speaks, know he was investigated in 2012.» — the testimony is already cracked.",a:{bait:"Someone about to say something credible.",hook:"Before they speak, negative info about them is seeded.",trap:"Whatever they say, the audience listens with preloaded suspicion."}},
  10:{s:"Half the truth, whole the lie.",h:"A flyer lists only the candidate's wins, never the losses. All true. All partial.",a:{bait:"A complex story with light and shadow.",hook:"Present only the favorable data, hide the rest.",trap:"No outright lie, but the final picture is warped."}},
  11:{s:"Give them a label and you'll never have to argue with them again.",h:"«He's a denier.» Two words replace the entire discussion with a category.",a:{bait:"A nuanced, articulated position.",hook:"Slap on a simple, emotionally charged label.",trap:"The label covers the person: you no longer argue with them, you argue with a category."}},
  12:{s:"If everyone does it, you must too. Even when you shouldn't.",h:"«72% of people agree with us.» — your brain rushes to join the 72%.",a:{bait:"The human need not to be left out.",hook:"Show a number, a movement, a crowd that \"already\" thinks this way.",trap:"You jump on the wagon to avoid exclusion, not because you evaluated."}},
  13:{s:"Shiny words that say nothing.",h:"«Freedom, future, change.» — applause. What does it mean concretely? No one asks.",a:{bait:"Values everyone shares and nobody challenges.",hook:"Use abstract, noble words without defining or committing.",trap:"You embrace the glow and accept whatever content gets slipped inside."}},
  14:{s:"Borrow someone else's authority by leaning on it.",h:"The politician in front of the flag, next to a national hero's statue: the message shifts without a single word.",a:{bait:"A respected symbol (flag, science, religion, hero).",hook:"Place your message next to the symbol.",trap:"The symbol's emotions transfer onto the message — with no evidence."}},
  15:{s:"A famous face instead of an argument.",h:"A beloved actor says «trust this drug»: they're not a doctor, but their face beats the data.",a:{bait:"The public's affection for a known figure.",hook:"That figure endorses a claim, a product, an idea.",trap:"Affection for the person becomes trust in the claim."}},
  16:{s:"Say something often enough and it becomes true.",h:"The same slogan at every interview, tweet, poster. After a month, you feel like you always believed it.",a:{bait:"A claim, true or false, you want to embed.",hook:"Repeat it identically, frequently, across channels.",trap:"Familiarity becomes credibility: to recognize is to believe."}},
  17:{s:"One short line can kill an hour of reasoning.",h:"Three words: any counter-argument sounds long, complicated, boring by comparison.",a:{bait:"A complex reality that needs explanation.",hook:"Compress it into a rhythmic, memorable, emotional formula.",trap:"The formula becomes the conclusion: critical thinking costs too much by comparison."}},
  18:{s:"The powerful in rolled-up sleeves isn't one of us — they're pretending.",h:"The billionaire in a hoodie, drinking beer at a small-town bar: «I'm just like you». (Spoiler: no.)",a:{bait:"Distrust of elites.",hook:"The one in charge dresses, talks, eats like «regular folks».",trap:"You trust them because they seem like you — and stop seeing the power they hold."}},
  19:{s:"A title is not evidence: check the field.",h:"«A Nobel laureate said...» — yes, but a Nobel in literature talking about medicine. The title dazzles.",a:{bait:"Instinctive respect for titles and credentials.",hook:"An authority is cited — often outside their field — as if settling the matter.",trap:"The prestige of the title replaces checking the argument."}},
  20:{s:"Break the middle. Only extremes. Only enemies.",h:"«You're with us or with them.» Anyone trying to mediate becomes a traitor to both sides.",a:{bait:"A society of many nuanced positions.",hook:"Reduce it all to two hostile, incompatible camps.",trap:"Anyone in the middle vanishes or becomes a target: dialogue is erased."}},
  21:{s:"Twenty lies in a minute: no one can rebut them all.",h:"In a debate, 15 shaky \"facts\" in 90 seconds. Refuting them would take half an hour. You don't have it.",a:{bait:"The limited time of a debate or interview.",hook:"Fire a burst of false or shaky claims too fast to unpack.",trap:"The opponent addresses a few; the rest remain unchallenged in the audience's mind."}},
  22:{s:"They're not attacking you: they're attacking a cartoon of you.",h:"«You want lower city speed limits?» → «So you want to ban cars!» — and the debate pivots to something you never said.",a:{bait:"A reasonable but hard-to-refute position.",hook:"Reframe it as an extreme, cartoonish version easy to attack.",trap:"They demolish the cartoon and you look defeated — for something you never said."}},
  23:{s:"A scented diversion, and the trail is lost.",h:"You ask about the budget: he talks about the football season. Halfway through, you've forgotten the question.",a:{bait:"An awkward, specific question.",hook:"Introduce an interesting but irrelevant topic.",trap:"The conversation follows the new trail; the original question dies."}},
  24:{s:"Accuse the other of what you're doing yourself.",h:"The politician knee-deep in scandal yells daily: «They're the corrupt ones!». The audience gets confused.",a:{bait:"A guilt of your own that might surface.",hook:"Accuse the opponent of the same act — first, and loudly.",trap:"Listeners struggle to see who's really guilty: the noise hides the trail."}},
  25:{s:"You speak to everyone, but only some hear the real message.",h:"A seemingly innocent phrase: «give our land back to those who deserve it». The insiders receive the coded meaning.",a:{bait:"A mixed audience to manage.",hook:"Use language that's neutral to most, coded for a subgroup.",trap:"If someone calls it out, just deny: «I never said that»."}},
  26:{s:"It makes you doubt what you saw with your own eyes.",h:"«That never happened.» «You imagined it.» «You're too sensitive.» — after months, you can't tell what's real.",a:{bait:"A real event, documented or lived.",hook:"Calmly, repeatedly deny it happened — or deny it was what it seemed.",trap:"The victim stops trusting their own memory and loses their compass."}},
  27:{s:"Pick the good cherries. Let the rotten rest under the tree.",h:"One study out of 100 backs the claim. It's cited as \"science says\". The other 99? Silence.",a:{bait:"A broad dataset, much of it against the claim.",hook:"Extract only the cases that confirm.",trap:"The sample becomes a statistical lie — without a single false statement."}},
  28:{s:"Fake grass: looks spontaneous, it's a rug.",h:"A \"citizens' association\" pops up in 50 cities the same day, same graphics. Nobody asks questions.",a:{bait:"The trust people place in grassroots movements.",hook:"Fund and stage a \"movement\" that mimics popular spontaneity.",trap:"The public thinks it sees the people's will; it's watching a paid ad."}},
  29:{s:"Hit yourself — and blame your enemy.",h:"An attack seemingly by group A is pinned on group B to justify cracking down on them.",a:{bait:"The need to justify a strong action.",hook:"Stage an aggression that looks like the opponent did it.",trap:"Public opinion demands revenge against an enemy who didn't act."}},
  30:{s:"Your eyes are no longer enough as evidence.",h:"A video of the leader saying things he never said. Viral in 6 hours. The correction, 6 days.",a:{bait:"The residual trust people still have in video and audio.",hook:"Synthesize a fake clip visually identical to the real thing.",trap:"Even after debunking, the emotional memory of the clip lingers."}},
  31:{s:"A war without weapons: the battlefield is your mind.",h:"Hundreds of fake accounts, coordinated articles, targeted memes: not a single act, an orchestrated campaign.",a:{bait:"An open, fragile information space.",hook:"State or private actors coordinate content, accounts, channels in long campaigns.",trap:"A nation's public debate gets shaped from outside — with no declaration of war."}},
  32:{s:"Don't hide the story: bury it under other stories.",h:"The day of the damaging investigation, a celebrity's private life explodes on the news: the investigation vanishes.",a:{bait:"An inconvenient story that would surface on its own.",hook:"Release many flashier pieces simultaneously.",trap:"Attention is a scarce resource: the important story never gets oxygen."}},
  33:{s:"Scare them and they won't think — they'll obey.",h:"«If we don't act today, tomorrow is too late!» — and any drastic measure becomes acceptable.",a:{bait:"A latent anxiety or a real danger.",hook:"Amplify the threat and offer an immediate, strong solution.",trap:"Terrified, the audience accepts trade-offs a calm mind would reject."}},
  34:{s:"The flag as argument: touch it, you're the enemy.",h:"«A true patriot would never doubt this measure.» — and dissent becomes treason.",a:{bait:"Emotional attachment to the nation.",hook:"Tie a specific claim to national identity.",trap:"Criticizing the claim means betraying the nation: dissent costs too much."}},
  35:{s:"It doesn't sell the product: it sells who you wish you were.",h:"A model laughs in a perfect kitchen holding a detergent. You're not buying the detergent: you're buying that life.",a:{bait:"The wish to resemble attractive, successful people.",hook:"Pair the product or idea with perfect bodies and lives.",trap:"Adopting the claim becomes the way to get closer to that image."}},
  36:{s:"«Last spots left!» shuts down your brain.",h:"«Only 3 left in stock!» — you click before asking whether you even need it.",a:{bait:"Fear of missing out.",hook:"Signal scarcity or urgency, real or invented.",trap:"The brain switches to \"act now\" mode and skips evaluation."}},
  37:{s:"A gift today is a chain tomorrow.",h:"You get a free sample. Now you feel you must give back — that's how your brain works.",a:{bait:"The universal social norm: «give and give back».",hook:"Offer a small favor or free gift.",trap:"The person feels a moral debt and gives back more than the gift was worth."}},
  38:{s:"The first number wins the negotiation, even when it's absurd.",h:"List price: $999. Now: $299. The «deal» exists only because you saw $999 first.",a:{bait:"The need for a reference point.",hook:"Throw out a first value (price, estimate, percent), high or low at will.",trap:"Every later evaluation orbits that anchor — however arbitrary it was."}},
  39:{s:"We hunt for what we already believe and call it evidence.",h:"You read only the paper that agrees with you. A year later, you're sure «everyone» thinks this way.",a:{bait:"The brain's natural tendency to confirm its beliefs.",hook:"Keep serving content aligned with your convictions.",trap:"You see the world as unanimous: doubt drops off the radar."}},
  40:{s:"Either black or white — everything else got erased.",h:"«Either you're with us or against us.» — the third, fourth, tenth option got swept away.",a:{bait:"A reality with many possible options.",hook:"Present only two, extreme and opposite.",trap:"You pick the \"lesser evil\" without seeing the hidden options."}},
  41:{s:"They flood you with love to tie a leash on you.",h:"In the early days you're flooded with attention, gifts, compliments. Months later, you can't leave.",a:{bait:"The universal need to feel seen and loved.",hook:"Saturate the target with sudden, intense affection.",trap:"When the love is withdrawn, you'll do anything to win it back: you're caught."}},
  42:{s:"You can't recover what you've already lost — but you try anyway.",h:"«I've already put in 5 years: I can't quit now.» — and you go lose another 5.",a:{bait:"A past, unrecoverable investment (time, money, emotions).",hook:"Invoke what's already spent as a reason to keep going.",trap:"You decide based on the past instead of the future: you sink deeper."}},
  43:{s:"One shiny trait makes other, nonexistent ones glow.",h:"The candidate is handsome and smiles: the audience attributes competence, honesty, intelligence. Without evidence.",a:{bait:"One evident, positive trait (beauty, fame, eloquence).",hook:"The brain extends that glow to other, unverified traits.",trap:"You judge the person on merits your own brain invented."}},
  44:{s:"«Natural» doesn't mean «good». Arsenic is natural.",h:"«It's a natural remedy!» — so is hemlock, and a viper bite. Natural too.",a:{bait:"The cultural charm around everything «natural».",hook:"Label something «natural» to imply goodness or safety.",trap:"The label replaces assessing risk, efficacy, and interactions."}},
  45:{s:"One small step today, the abyss tomorrow (so they say).",h:"«If we allow A, in ten years we'll have Z.» — without ever explaining what happens from B through Y.",a:{bait:"A reasonable, limited proposal.",hook:"Project a chain of catastrophic outcomes with no intermediate steps.",trap:"Fear of the final outcome blocks discussion of the first step, which was harmless."}},
  46:{s:"Two comparable things aren't automatically equal.",h:"«Both parties have scandals.» Yes — one has 3 investigations, the other 300. Equality is rhetoric, not reality.",a:{bait:"Two situations comparable on some aspect.",hook:"Treat them as equal, ignoring scale, severity, context.",trap:"The audience concludes «they're the same» — and the worse side profits."}},
  47:{s:"A complex problem, one group to blame.",h:"Stagnant economy? Their fault. Unemployment? Their fault. A packed stadium? Their fault. Easy.",a:{bait:"A real, widespread collective unease.",hook:"Pick a group to dump all responsibility on.",trap:"Analysis of the real causes stops: punishing the scapegoat is enough."}},
  48:{s:"Guilt denied, victim flipped.",h:"He's accused. Denies everything. Attacks the accuser. Poses as a victim of the investigation. In 30 seconds.",a:{bait:"A founded accusation against someone with power.",hook:"Deny, attack the accuser, flip who's the victim and who's the aggressor.",trap:"The confused audience loses track of who's hurt and who's doing harm."}},
  49:{s:"Yesterday unthinkable. Today debatable. Tomorrow the law.",h:"An extreme idea gets calmly repeated for years. First time it scandalizes. Five years on, it's mainstream debate.",a:{bait:"The range of what a society sees as sayable.",hook:"Introduce extreme ideas that nudge the edges over time.",trap:"What was once taboo becomes normal — without anyone explicitly deciding."}},
  50:{s:"You think you're alone, so you stay silent. That's how you become alone.",h:"On social feeds it looks like everyone agrees. You don't — but you stay quiet. Others like you see the silence and stay quiet too.",a:{bait:"Fear of social isolation.",hook:"Amplify one voice and muffle the rest, creating the illusion of majority.",trap:"Dissenters stay silent out of fear — and their silence confirms the illusion."}},
  51:{s:"Every time you reach the goal, the goal moves.",h:"«Prove X.» — you do. «Yeah, but now prove Y.» — you do. «Yeah, but now prove Z.» The game never ends.",a:{bait:"A clear request for proof or a condition.",hook:"Every time it's met, replace it with a new one.",trap:"The opponent can never «win»: the debate is rigged to never end."}},
  52:{s:"A poisoned compliment ties you to the giver.",h:"«You're cute — for someone like you.» — you feel insecure. You want approval. You seek it from him.",a:{bait:"The target's self-esteem.",hook:"Slip subtle put-downs inside compliments.",trap:"Destabilized, the target seeks approval from the very person who destabilized them."}},
  53:{s:"You don't think: you feel. And you feel what the others feel.",h:"An outraged post gets shared 10,000 times. Before you even read it, you're already angry too.",a:{bait:"Natural emotional synchronization between humans.",hook:"Spread high-emotion content fast.",trap:"Collective emotion overrides individual thought: you act before you reflect."}},
  54:{s:"Make noise where you don't want them looking.",h:"While parliament passes a controversial law, a \"scandal\" erupts that takes over every newscast.",a:{bait:"A real problem that would otherwise draw critical attention.",hook:"Generate or amplify a distracting event.",trap:"When the smoke clears, the real problem is already a done deal."}},
  55:{s:"Predict the collapse — and make it happen.",h:"«That bank is shaky.» Everyone runs to withdraw. The bank fails. Was it really shaky? Now it is.",a:{bait:"A forecast inside a system where expectations shape outcomes.",hook:"Spread the forecast as fact, changing collective behavior.",trap:"The changed behavior produces the forecast outcome, «confirming» the prophecy."}},
  56:{s:"The algorithm agrees with you to keep you hooked.",h:"Six months in, your feed is only things that confirm what you think. The world feels small and consistent.",a:{bait:"The human craving for «interesting» content.",hook:"The algorithm learns what keeps you hooked and feeds more of it.",trap:"You lose touch with different views: you mistake your bubble for the world."}}
};

function inject(filePath, map) {
  const data = JSON.parse(fs.readFileSync(filePath, 'utf8'));
  data.forEach(t => {
    const e = map[t.id];
    if (!e) { console.warn('Missing id', t.id, 'in', filePath); return; }
    t.slogan = e.s;
    t.hook = e.h;
    t.anatomy = { bait: e.a.bait, hook: e.a.hook, trap: e.a.trap };
  });
  fs.writeFileSync(filePath, JSON.stringify(data, null, 2) + '\n');
  console.log('Updated', filePath);
}

const root = path.resolve(__dirname, '..');
inject(path.join(root, 'locales/it/techniques.json'), IT);
inject(path.join(root, 'locales/en/techniques.json'), EN);
